### ISSUE TITLE
Not using full list of Alphabets, instead excluding some of characters in config.json

### ISSUE THREAD

**Issue by krisbianprabowo** [Wikidepia/indonesian-tts#1]
Hello, i'm relatively new in TTS and found your repository that you are actually supporting Bahasa for a TTS projects.
First allow me to say that I'm so glad i have found your works and really appreciate for what you have been doing through your works. I would ask you some question if you don't mind it.

So basically, i'm figuring it out what's inside your `config.json` and found that the list of characters you were using is something like this 
`"characters": "abdefhijklmnoprstuwxz\u014b\u0254\u0259\u025b\u0261\u026a\u0272\u0283\u028a\u0292\u0294\u02c8"`
Why instead using the list of full alphabets `(a-z)` + commonly used phonemes in Bahasa, you were excluding some of characters like `c, g, q, v`? 
I'm really grateful and would say many thanks if you are able to giving me the reason behind it.

**Comment by Wikidepia** [comment]
Hi, I use g2p-id to convert grapheme to phoneme first

https://github.com/Wikidepia/g2p-id.

**Comment by krisprabowo** [comment]
> Hi, I use g2p-id to convert grapheme to phoneme first
> 
> https://github.com/Wikidepia/g2p-id.

Oh wow, it makes sense now. Thank you for the replies!

**Comment by krisbianprabowo** [comment]
> Hi, I use g2p-id to convert grapheme to phoneme first
> 
> https://github.com/Wikidepia/g2p-id.

Oh wow, it makes sense now. Thank you for the replies!
