### ISSUE TITLE
Improve the vocabulary

### ISSUE THREAD

**Issue by jerichosiahaya** [Wikidepia/indonesian-tts#4]
Hello! First of all, thank you for providing this project. I'm a beginner in TTS, and I'm curious why in your model you don't include the number characters such as `1, 2, 9, 10`? Because when I run your model, the TTS show

```
 [!] Character '9' not found in the vocabulary. Discarding it.
```
Do you have any idea how to handle this? I was thinking two options: fine-tune the model again or handle the number characters (preprocessing the text).

**Comment by Wikidepia** [comment]
You need to convert the number to text

**Comment by jerichosiahaya** [comment]
Yes, I was thinking to do that too, but I'm just curious why it can't handle the number? Is it because the datasets? Or something?

I must have missed to try the original model, because I thought it only didn't work on yours. My mistake, sorry.
